
--Table Fait Commercial aggrégé par mois, année, commercial et les differents statuts (impaye/paye), (echoir,echu)
DROP TABLE FAIT_COMMERCIAL;
CREATE TABLE FAIT_COMMERCIAL AS
SELECT 
    A_DEMANDE.UTILISATEUR_ID,
    SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE,
    SUM(CRD) AS CRD_DEMANDE,
    A_DOSSIER.IMPAYE,
    A_DOSSIER.TERME,
    COUNT(A_DEMANDE.DEMANDE_ID) AS NBRE_DEMANDE,
    (SELECT DTE_ID FROM DATE_DTE 
        WHERE 
            DTE_YEAR = EXTRACT(year FROM A_DEMANDE.CREATION_DATE)
        AND
            DTE_MONTH = EXTRACT(month FROM A_DEMANDE.CREATION_DATE)
    ) AS DATE_DTE_ID
FROM A_DEMANDE 
INNER JOIN A_DOSSIER ON A_DEMANDE.DEMANDE_ID = A_DOSSIER.DOSSIER_ID
GROUP BY 
    A_DEMANDE.UTILISATEUR_ID, 
    A_DOSSIER.IMPAYE,
    A_DOSSIER.TERME,
    EXTRACT(year FROM A_DEMANDE.CREATION_DATE),
    EXTRACT(month FROM A_DEMANDE.CREATION_DATE)
ORDER BY DATE_DTE_ID;

--Table Fait Partenaire aggrégé par mois, année, paretnaire et les differents statuts (impaye/paye), (echoir,echu)
DROP TABLE FAIT_PARTENAIRE;
CREATE TABLE FAIT_PARTENAIRE AS
SELECT 
    A_UTILISATEUR.ACT_ID,
    A_ACTEUR.CAPITAL_SOCIAL,
    SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE,
    SUM(CRD) AS CRD_DEMANDE,
    A_DOSSIER.IMPAYE,
    A_DOSSIER.TERME,
    COUNT(A_DEMANDE.DEMANDE_ID) AS NBRE_DEMANDE,
    (SELECT DTE_ID FROM DATE_DTE 
        WHERE 
            DTE_YEAR = EXTRACT(year FROM A_DEMANDE.CREATION_DATE)
        AND
            DTE_MONTH = EXTRACT(month FROM A_DEMANDE.CREATION_DATE)
    ) AS DATE_DTE_ID
FROM A_DEMANDE 
INNER JOIN A_DOSSIER ON A_DEMANDE.DEMANDE_ID = A_DOSSIER.DOSSIER_ID
INNER JOIN A_UTILISATEUR ON A_DEMANDE.UTILISATEUR_ID = A_UTILISATEUR.UTILISATEUR_ID
INNER JOIN A_ACTEUR ON A_ACTEUR.ACT_ID = A_UTILISATEUR.ACT_ID
GROUP BY 
    A_UTILISATEUR.ACT_ID,
    A_ACTEUR.CAPITAL_SOCIAL,
    A_DOSSIER.IMPAYE,
    A_DOSSIER.TERME,
    EXTRACT(year FROM A_DEMANDE.CREATION_DATE),
    EXTRACT(month FROM A_DEMANDE.CREATION_DATE)
ORDER BY DATE_DTE_ID;

--Table Fait Fournisseur aggrégé par fornisseur et par statut (echoir,echu)
DROP TABLE FAIT_FOURNISSEUR;
CREATE TABLE FAIT_FOURNISSEUR AS
SELECT
    A_DEMANDE.FOURNISSEUR_ID,
    COUNT(A_DEMANDE.DEMANDE_ID) AS NBRE_DEMANDE,
    SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE,
    A_DEMANDE.TERME
FROM A_DEMANDE 
WHERE A_DEMANDE.FOURNISSEUR_ID IS NOT NULL
GROUP BY A_DEMANDE.FOURNISSEUR_ID, A_DEMANDE.TERME;

--Table Fait Garant aggrégé par garant et par statut (echoir,echu)
DROP TABLE FAIT_GARANT;
CREATE TABLE FAIT_GARANT AS
SELECT
    A_DEMANDE.GARANT_ID,
    A_ACTEUR.CAPITAL_SOCIAL,
    SUM(A_DOSSIER.CRD) AS CRD_TOTAL,
    COUNT(A_DEMANDE.DEMANDE_ID) AS NBRE_DEMANDE,
    SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE,
    A_DEMANDE.TERME
FROM A_DEMANDE
INNER JOIN A_DOSSIER ON A_DEMANDE.DEMANDE_ID = A_DOSSIER.DOSSIER_ID
INNER JOIN A_ACTEUR ON A_DEMANDE.GARANT_ID = A_ACTEUR.ACT_ID
WHERE A_DEMANDE.GARANT_ID IS NOT NULL
GROUP BY
    A_DEMANDE.GARANT_ID,
    A_ACTEUR.CAPITAL_SOCIAL,
    A_DEMANDE.TERME;