
SET SERVEROUTPUT ON

INSERT INTO COMMERCIAL_CMC (CMC_ID, CMC_NOM, CMC_PRENOM)
SELECT UTILISATEUR_ID, NOM, PRENOM FROM A_UTILISATEUR;

ALTER TABLE FOURNISSEUR_FNS
DROP COLUMN FNS_PRENOM;

insert into FOURNISSEUR_FNS 
Select ACT_ID,NOM,SIRET from A_ACTEUR WHERE A_ACTEUR.TYPE_ACTEUR = 'FOURN';

declare 
    d_dateD DATE := (SELECT Min(CREATION_DATE) FROM A_DEMANDE);
    d_dateF DATE := (SELECT Max(CREATION_DATE) FROM A_DEMANDE)
    
BEGIN

WHILE d_dateD < d_dateF

        INSERT INTO DATE_DTE (DTE_DATE, DTE_YEAR,DTE_MONTH)
        VALUES (d_dateD, YEAR(d_dateD),MONTH(d_dateD))
  SET d_dateD = DATEADD(MONTH, 1, d_dateD)
END 
SELECT * FROM DATE_DTE;

 
SELECT* FROM FOURNISSEUR_FNS;





declare 
    d_dateD A_DEMANDE.CREATION_DATE%TYPE;
    d_dateF A_DEMANDE.CREATION_DATE%TYPE;
    
BEGIN
    SELECT MIN(CREATION_DATE) 
    INTO d_dateD
    FROM A_DEMANDE;
    
    SELECT MAX(CREATION_DATE) 
    INTO d_dateF
    FROM A_DEMANDE;
     
     DBMS_OUTPUT.PUT_LINE(d_dateD);
     DBMS_OUTPUT.PUT_LINE(d_dateF);
     
     WHILE d_dateD < d_dateF
     LOOP 
     
     INSERT INTO DATE_DTE (DTE_DATE, DTE_YEAR,DTE_MONTH)
        VALUES (d_dateD, YEAR(d_dateD),MONTH(d_dateD))
     SET d_dateD = DATEADD(MONTH, 1, d_dateD)
     
     
     END LOOP;
     
     
END;