
--Table Fait Commercial aggrégé par mois, année, commercial et les differents statuts (impaye/paye), (echoir,echu)
CREATE TABLE FAIT_COMMERCIAL AS
SELECT A_DEMANDE.UTILISATEUR_ID, count(A_DEMANDE.DEMANDE_ID) as NBRE_DEMANDE, extract(year from A_DEMANDE.CREATION_DATE) as YEAR_DEMANDE,  extract(month from A_DEMANDE.CREATION_DATE) as MONTH_DEMANDE, SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE, SUM(CRD) AS CRD_DEMANDE,A_DOSSIER.IMPAYE, A_DOSSIER.TERME
FROM A_DEMANDE 
INNER JOIN A_DOSSIER 
ON A_DEMANDE.DEMANDE_ID = A_DOSSIER.DOSSIER_ID
GROUP BY A_DEMANDE.UTILISATEUR_ID, extract(year from A_DEMANDE.CREATION_DATE),  extract(month from A_DEMANDE.CREATION_DATE),A_DOSSIER.IMPAYE, A_DOSSIER.TERME
order by YEAR_DEMANDE, MONTH_DEMANDE;

--Table Fait Partenaire aggrégé par mois, année, paretnaire et les differents statuts (impaye/paye), (echoir,echu)
CREATE TABLE FAIT_PARTENAIRE AS
SELECT A_UTILISATEUR.ACT_ID,A_ACTEUR.CAPITAL_SOCIAL, count(A_DEMANDE.DEMANDE_ID) as NBRE_DEMANDE, extract(year from A_DEMANDE.CREATION_DATE) as YEAR_DEMANDE,  extract(month from A_DEMANDE.CREATION_DATE) as MONTH_DEMANDE, SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE, SUM(CRD) AS CRD_DEMANDE,A_DOSSIER.IMPAYE, A_DOSSIER.TERME
FROM A_DEMANDE 
INNER JOIN A_DOSSIER 
ON A_DEMANDE.DEMANDE_ID = A_DOSSIER.DOSSIER_ID
INNER JOIN A_UTILISATEUR 
ON A_DEMANDE.UTILISATEUR_ID = A_UTILISATEUR.UTILISATEUR_ID
INNER JOIN A_ACTEUR 
ON A_ACTEUR.ACT_ID = A_UTILISATEUR.ACT_ID
GROUP BY A_UTILISATEUR.ACT_ID,A_ACTEUR.CAPITAL_SOCIAL, extract(year from A_DEMANDE.CREATION_DATE),  extract(month from A_DEMANDE.CREATION_DATE),A_DOSSIER.IMPAYE, A_DOSSIER.TERME
order by YEAR_DEMANDE, MONTH_DEMANDE;

--Table Fait Fournisseur aggrégé par fornisseur et par statut (echoir,echu)
CREATE TABLE FAIT_FOURNISSEUR AS
SELECT A_DEMANDE.FOURNISSEUR_ID, count(A_DEMANDE.DEMANDE_ID) as NBRE_DEMANDE, SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE, A_DEMANDE.TERME
FROM A_DEMANDE 
WHERE A_DEMANDE.FOURNISSEUR_ID IS NOT NULL
GROUP BY A_DEMANDE.FOURNISSEUR_ID, A_DEMANDE.TERME;

--Table Fait Garant aggrégé par garant et par statut (echoir,echu)
CREATE TABLE FAIT_GARANT AS
SELECT A_DEMANDE.GARANT_ID, count(A_DEMANDE.DEMANDE_ID) as NBRE_DEMANDE, SUM(A_DEMANDE.MONTANT) AS MONTANT_DEMANDE, A_DEMANDE.TERME
FROM A_DEMANDE 
WHERE A_DEMANDE.GARANT_ID IS NOT NULL
GROUP BY A_DEMANDE.GARANT_ID, A_DEMANDE.TERME;