-----------------------------
-- Statistiques Commercial --
-----------------------------
-- Nombre total de demandes
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM AS "nom de commercial", 
  SUM(BI_2.FAIT_COMMERCIAL.NBRE_DEMANDE) AS "nombre de demandes acceptees"
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

-- Nombre de demandes sur les 2 derniers mois
SELECT
  BI_2.COMMERCIAL_CMC.CMC_NOM AS "nom de commercial", 
  SUM(BI_2.FAIT_COMMERCIAL.NBRE_DEMANDE) AS "demandes acceptees 2m"
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
  WHERE BI_2.FAIT_COMMERCIAL.DATE_DTE_ID IN (
    SELECT BI_2.DATE_DTE.DTE_ID 
    FROM BI_2.DATE_DTE
    WHERE DTE_DATE > ADD_MONTHS(CURRENT_DATE, -2))
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

--Nombre de demandes avec Impayées
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM  AS "nom de commercial", 
  SUM(BI_2.FAIT_COMMERCIAL.NBRE_DEMANDE) AS "nombre de demandes impayées"
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
  WHERE BI_2.FAIT_COMMERCIAL.IMPAYE = 'O'
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

--Total chiffre d'affaires réalisé
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM AS "nom de commercial", 
  SUM(BI_2.FAIT_COMMERCIAL.MONTANT_DEMANDE) AS "montant de demande"
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

-- Nombre de demandes cloturées
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM AS "nom de commercial", 
  SUM(BI_2.FAIT_COMMERCIAL.NBRE_DEMANDE) AS "nombre de demandes cloturées"
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
  WHERE BI_2.FAIT_COMMERCIAL.TERME = 'ECHU'
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

-- Total Du CRD de l'ensemble de demandes
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM AS "nom de commercial", 
  SUM(BI_2.FAIT_COMMERCIAL.CRD_DEMANDE) AS "montant de CRD_DEMANDE"
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

-- Total chiffre d'affaires réalisé année en cours
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM, 
  SUM(BI_2.FAIT_COMMERCIAL.MONTANT_DEMANDE)
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
  WHERE BI_2.FAIT_COMMERCIAL.DATE_DTE_ID IN (
    SELECT BI_2.DATE_DTE.DTE_ID 
    FROM BI_2.DATE_DTE
    WHERE BI_2.DATE_DTE.DTE_YEAR = EXTRACT(year FROM CURRENT_DATE))
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;

-- Total chiffre d'affaires réalisé mois en cours
SELECT 
  BI_2.COMMERCIAL_CMC.CMC_NOM, 
  SUM(BI_2.FAIT_COMMERCIAL.MONTANT_DEMANDE)
  FROM BI_2.FAIT_COMMERCIAL
  INNER JOIN BI_2.COMMERCIAL_CMC 
    ON BI_2.COMMERCIAL_CMC.CMC_ID = BI_2.FAIT_COMMERCIAL.UTILISATEUR_ID
  WHERE BI_2.FAIT_COMMERCIAL.DATE_DTE_ID IN (
    SELECT BI_2.DATE_DTE.DTE_ID 
    FROM BI_2.DATE_DTE
    WHERE BI_2.DATE_DTE.DTE_MONTH = EXTRACT(month FROM CURRENT_DATE))
GROUP BY  BI_2.COMMERCIAL_CMC.CMC_NOM;



-----------------------------
-- Statistiques Partenaire --
-----------------------------
-- Nombre total de demandes
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.NBRE_DEMANDE) AS "Nombre total de demande"
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

-- Nombre de demandes sur les 2 derniers mois
SELECT
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.NBRE_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
  WHERE BI_2.FAIT_PARTENAIRE.DATE_DTE_ID IN (
    SELECT BI_2.DATE_DTE.DTE_ID 
    FROM BI_2.DATE_DTE
    WHERE DTE_DATE > ADD_MONTHS(CURRENT_DATE, -2))
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

--Nombre de demandes avec Impayées
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.NBRE_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
  WHERE BI_2.FAIT_PARTENAIRE.IMPAYE = 'O'
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

--Total chiffre d'affaires réalisé
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.MONTANT_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

-- Nombre de demandes cloturées
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.NBRE_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
  WHERE BI_2.FAIT_PARTENAIRE.TERME = 'ECHU'
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

-- Total Du CRD de l'ensemble de demandes
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.CRD_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

-- Total chiffre d'affaires réalisé année en cours
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.MONTANT_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
  WHERE BI_2.FAIT_PARTENAIRE.DATE_DTE_ID IN (
    SELECT BI_2.DATE_DTE.DTE_ID 
    FROM BI_2.DATE_DTE
    WHERE BI_2.DATE_DTE.DTE_YEAR = EXTRACT(year FROM CURRENT_DATE))
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

-- Total chiffre d'affaires réalisé mois en cours
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_PARTENAIRE.MONTANT_DEMANDE)
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
  WHERE BI_2.FAIT_PARTENAIRE.DATE_DTE_ID IN (
    SELECT BI_2.DATE_DTE.DTE_ID 
    FROM BI_2.DATE_DTE
    WHERE BI_2.DATE_DTE.DTE_MONTH = EXTRACT(month FROM CURRENT_DATE))
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;

-- Total CRD>Capital Social?
SELECT 
  BI_2.PARTENAIRE_PTN.PTN_NOM AS "Partenaire Nom",
  (CASE WHEN 
    SUM(BI_2.FAIT_PARTENAIRE.CRD_DEMANDE) 
    > 
    SUM(BI_2.FAIT_PARTENAIRE.CAPITAL_SOCIAL) 
    THEN 1 ELSE 0 END) AS "CRD>Capital Social?",
  SUM(BI_2.FAIT_PARTENAIRE.CRD_DEMANDE) AS CRD, 
  SUM(BI_2.FAIT_PARTENAIRE.CAPITAL_SOCIAL) AS "Capital Social"
  FROM BI_2.FAIT_PARTENAIRE
  INNER JOIN BI_2.PARTENAIRE_PTN 
    ON BI_2.PARTENAIRE_PTN.PTN_ID = BI_2.FAIT_PARTENAIRE.ACT_ID
GROUP BY  BI_2.PARTENAIRE_PTN.PTN_NOM;



------------------------------
-- Statistiques Fournisseur --
------------------------------
-- Nombre total de demandes
SELECT 
  BI_2.FOURNISSEUR_FNS.FNS_NOM, 
  SUM(BI_2.FAIT_FOURNISSEUR.NBRE_DEMANDE)
  FROM BI_2.FAIT_FOURNISSEUR
  INNER JOIN BI_2.FOURNISSEUR_FNS 
    ON BI_2.FOURNISSEUR_FNS.FNS_ID = BI_2.FAIT_FOURNISSEUR.FOURNISSEUR_ID
GROUP BY  BI_2.FOURNISSEUR_FNS.FNS_NOM;

-- Total chiffre d'affaires réalisé
SELECT 
  BI_2.FOURNISSEUR_FNS.FNS_NOM AS "Partenaire Nom", 
  SUM(BI_2.FAIT_FOURNISSEUR.MONTANT_DEMANDE)
  FROM BI_2.FAIT_FOURNISSEUR
  INNER JOIN BI_2.FOURNISSEUR_FNS 
    ON BI_2.FOURNISSEUR_FNS.FNS_ID = BI_2.FAIT_FOURNISSEUR.FOURNISSEUR_ID
GROUP BY  BI_2.FOURNISSEUR_FNS.FNS_NOM;

-- Nombre de demandes cloturées
SELECT 
  BI_2.FOURNISSEUR_FNS.FNS_NOM, 
  SUM(BI_2.FAIT_FOURNISSEUR.NBRE_DEMANDE)
  FROM BI_2.FAIT_FOURNISSEUR
  INNER JOIN BI_2.FOURNISSEUR_FNS 
    ON BI_2.FOURNISSEUR_FNS.FNS_ID = BI_2.FAIT_FOURNISSEUR.FOURNISSEUR_ID
  WHERE BI_2.FAIT_FOURNISSEUR.TERME = 'ECHU'
GROUP BY  BI_2.FOURNISSEUR_FNS.FNS_NOM;

-------------------------
-- Statistiques Garant --
-------------------------
-- Nombre total de demandes
SELECT 
  BI_2.GARANT_GRT.GRT_NOM, 
  SUM(BI_2.FAIT_GARANT.NBRE_DEMANDE)
  FROM BI_2.FAIT_GARANT
  INNER JOIN BI_2.GARANT_GRT 
    ON BI_2.GARANT_GRT.GRT_ID = BI_2.FAIT_GARANT.GARANT_ID
GROUP BY  BI_2.GARANT_GRT.GRT_NOM;

-- Total chiffre d'affaires réalisé
SELECT 
  BI_2.GARANT_GRT.GRT_NOM AS "Garant Nom", 
  SUM(BI_2.FAIT_GARANT.MONTANT_DEMANDE)
  FROM BI_2.FAIT_GARANT
  INNER JOIN BI_2.GARANT_GRT 
    ON BI_2.GARANT_GRT.GRT_ID = BI_2.FAIT_GARANT.GARANT_ID
GROUP BY  BI_2.GARANT_GRT.GRT_NOM;

-- Nombre de demandes cloturées
SELECT 
  BI_2.GARANT_GRT.GRT_NOM, 
  SUM(BI_2.FAIT_GARANT.NBRE_DEMANDE)
  FROM BI_2.FAIT_GARANT
  INNER JOIN BI_2.GARANT_GRT 
    ON BI_2.GARANT_GRT.GRT_ID = BI_2.FAIT_GARANT.GARANT_ID
  WHERE BI_2.FAIT_GARANT.TERME = 'ECHU'
GROUP BY  BI_2.GARANT_GRT.GRT_NOM;

-- Total CRD>Capital Social?
SELECT 
  BI_2.GARANT_GRT.GRT_NOM AS "Garant Nom",
  (CASE WHEN 
    SUM(BI_2.FAIT_GARANT.CRD_TOTAL) 
    > 
    SUM(BI_2.FAIT_GARANT.CAPITAL_SOCIAL) 
    THEN 1 ELSE 0 END) AS "CRD>Capital Social?",
  SUM(BI_2.FAIT_GARANT.CRD_TOTAL) AS CRD,
  AVG(BI_2.GARANT_GRT.GRT_CAPITALSOCIAL) AS "Capital Social"
  FROM BI_2.FAIT_GARANT
  INNER JOIN BI_2.GARANT_GRT 
    ON BI_2.GARANT_GRT.GRT_ID = BI_2.FAIT_GARANT.GARANT_ID
GROUP BY  BI_2.GARANT_GRT.GRT_NOM;
